CREATE TABLE barcode.new_books (
    input_identifier STRING,
    isbn STRING,
    lccn STRING,
    title STRING,
    author STRING,
    call_number STRING,
    holding_barcode STRING,
    series_title STRING,
    series_number STRING,
    copyright_year STRING,
    publication_date STRING,
    cost FLOAT64,
    price FLOAT64,
    description STRING,
    summary STRING,
    subject_headings STRING,
    notes STRING,
    dust_jacket_url STRING,
    raw_marc STRING,
    enriched_marc STRING,
    status STRING,
    last_modified TIMESTAMP
);
